### ISSUE TITLE
spots card

### ISSUE THREAD

**Issue by zimb0o** [zimb0o/capstone-project#2]
![3AAAE543-28A3-4281-BC88-65EB0617A5ED](https://user-images.githubusercontent.com/126156598/234313124-86d1ba8f-8965-4cf2-9773-b081b3188008.png)

**Comment by Roland-Hufnagel** [comment]
It still needs some detail work: 
please use the issue-template that is already in your repository.
Delete the header and footer from the wireframe because this is not part of this userstory.
Also favorite button and location Button.
Scroll vertically is not an acceptance criteria.
Delete non-used points from the description.

**Comment by zimb0o** [comment]
Card
as a user 
i want to see all the calisthenics spots, which are available
in order to decide which spot i can visit


Description
[image of wireframe]

Acceptance criteria
 criteria 1
 criteria 2
Tasks
 task 1
 task 2

**Comment by NikRoe** [comment]
Hi Alex,

starting now, please use the user story template when creating a new issue (you can keep your existing issues as they are, but all following issues should use the user story template.)

Your user story looks good overall, however, there are a few things that you should improve:

- your Description should not be a screenshot of the whole user story in excalidraw. Instead, it should only be the wireframe that shows an example how this new features looks after implementation
- in your Acceptance Criteria you should also mention that an image is displayed
- what do you mean with the "image window" in your Tasks? Will it be a component?
- in your wireframe you mention "weitere Details" -> This should be a separate user story and also not visible in the wireframe

**Comment by zimb0o** [comment]
Hi Niklas,

Here are the corrected sentences based on your message:

I have updated the screenshot.
I want to create a field where users can upload a picture or view a picture that already shows the location, but I will figure that out in another user story.
The "weitere Details" are no longer attached.

Pls let me know if this is alright

**Comment by NikRoe** [comment]
Hi Alex,

we are getting there!

You should replace the placeholders (name and location) with real data in your wireframe.

Since you removed the image part from your Tasks and Acceptance Criteria, you should also remove it from your wireframe.

Uploading images and storing them someplace will definitely be a separate user story and I would recommend postponing that story to another sprint. We will be offering a workshop for "Cloudinary" which will be the tool used exactly for this purpose.

If you want images to be shown earlier, you could start with dummy data. This could even part of this user story already.
This decision is up to you :)

**Comment by zimb0o** [comment]
Hey Niklas,

i updated the image and removed the image part from my Tasks and Acceptance Criteria.

If this is alright, i can upload my next userstorys :)

**Comment by NikRoe** [comment]
Yes, this looks good now!
